# Generated by Django 4.1.3 on 2022-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photo')),
                ('about', models.TextField()),
            ],
        ),
    ]
